# Generated by Django 3.1 on 2020-08-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line2',
        ),
        migrations.AlterField(
            model_name='address',
            name='addresstype',
            field=models.CharField(choices=[('delivery', 'Delivery')], max_length=120),
        ),
    ]
