# Generated by Django 3.1 on 2020-08-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20200828_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_line2',
            field=models.CharField(default='Kangemi', max_length=120),
        ),
    ]
