# Generated by Django 3.1 on 2020-09-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_auto_20200906_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytime',
            name='time',
            field=models.CharField(blank=True, choices=[('a', '8:00 AM - 10:00 AM'), ('b', '10:00 AM - 12:00 PM'), ('c', '12:00 PM - 2:00 PM'), ('d', '2:00 PM - 4:00 PM'), ('e', '4:00 PM - 6:00 PM')], max_length=150, null=True),
        ),
    ]
