# Generated by Django 3.1 on 2020-09-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0009_auto_20200912_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='estate_decsription',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
