# Generated by Django 3.1 on 2020-09-05 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20200906_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartquantity',
            name='price',
        ),
    ]
