# Generated by Django 3.1 on 2020-09-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200902_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('cash', 'Cash on Delivery')], default='created', max_length=120),
        ),
    ]
