# Generated by Django 3.1 on 2020-09-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_at_hand',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='order',
            name='change_expected',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
