# Generated by Django 3.1 on 2020-08-23 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('category_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_quantity_in_kgs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_discount_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_status', models.CharField(choices=[('Ac', 'Active'), ('In', 'InActive')], max_length=2)),
                ('product_Image_Field', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
