# Generated by Django 3.1 on 2020-08-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_Image_Field',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
