# Generated by Django 3.1 on 2020-08-23 00:55

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200823_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.FileField(null=True, upload_to=products.models.upload_image_path2),
        ),
    ]
