# Generated by Django 3.1 on 2020-08-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200823_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='featured_product',
            field=models.BooleanField(default=False),
        ),
    ]
