# Generated by Django 3.1 on 2020-08-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_featured_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
