# Generated by Django 3.1 on 2020-08-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(default='category1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_slug',
            field=models.SlugField(default='category2'),
            preserve_default=False,
        ),
    ]
