# Generated by Django 3.1 on 2020-08-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200823_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_slug',
            new_name='slug',
        ),
    ]
