# Generated by Django 3.1 on 2020-08-24 05:13

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200823_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_Image_Field',
            field=models.ImageField(upload_to=products.models.upload_image_path),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_images', models.ImageField(null=True, upload_to=products.models.upload_image_path)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
