# Generated by Django 3.1 on 2020-08-24 05:14

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200824_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_Image_Field',
            field=models.ImageField(null=True, upload_to=products.models.upload_image_path),
        ),
    ]
