# Generated by Django 3.1 on 2020-08-24 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200824_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreProductQuantirty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_product_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
