# Generated by Django 3.1 on 2020-08-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200824_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_status',
        ),
        migrations.AddField(
            model_name='products',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
