# Generated by Django 3.1 on 2020-09-08 00:21

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200824_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Image_Field', models.ImageField(null=True, upload_to=products.models.upload_image_path)),
            ],
        ),
    ]
