# Generated by Django 3.1 on 2020-09-08 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_banners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='MoreProductQuantirty',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
